# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dealers', '0001_initial'),
        ('tradeins', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.PositiveSmallIntegerField()),
                ('vehicle_colour', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=10)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('offered_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('availability_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('terms', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=15)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='dealers.dealer')),
                ('trade_in_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tradeins.tradeinrequest')),
            ],
            options={
                'db_table': 'dealer_offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('vehicle_type', models.CharField(max_length=10)),
                ('vehicle_category', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('preferred_make', models.CharField(blank=True, max_length=100)),
                ('preferred_model', models.CharField(blank=True, max_length=100)),
                ('preferred_year_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('preferred_year_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('arrangement_type', models.CharField(choices=[('LEASE', 'Lease'), ('PURCHASE', 'Purchase')], max_length=10)),
                ('selected_services', models.JSONField(default=list)),
                ('duration_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('requirements_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('DEALERS_ASSIGNED', 'Dealers Assigned'), ('OFFERS_RECEIVED', 'Offers Received'), ('OFFER_SELECTED', 'Offer Selected'), ('APPROVED', 'Approved'), ('CONTRACTED', 'Contracted'), ('ACTIVE', 'Active')], db_index=True, default='DRAFT', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_dealers', models.ManyToManyField(blank=True, related_name='procurement_requests', to='dealers.dealer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to='clients.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_procurement', to=settings.AUTH_USER_MODEL)),
                ('selected_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_for', to='procurement.dealeroffer')),
            ],
            options={
                'db_table': 'procurement_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dealeroffer',
            name='procurement_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='procurement.procurementrequest'),
        ),
    ]
