# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('REQUEST_APPROVED', 'Request Approved'), ('REQUEST_REJECTED', 'Request Rejected'), ('DEALER_ASSIGNED', 'Dealer Assigned'), ('OFFER_SUBMITTED', 'Offer Submitted'), ('INVOICE_SENT', 'Invoice Sent'), ('INVOICE_OVERDUE', 'Invoice Overdue'), ('MAINTENANCE_UPDATE', 'Maintenance Update'), ('INSURANCE_EXPIRY', 'Insurance Expiry Reminder'), ('LICENSE_EXPIRY', 'License Expiry Reminder'), ('CONTRACT_EXPIRY', 'Contract Expiry Reminder'), ('TRACKING_RENEWAL', 'Tracking Renewal Reminder'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
