# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('selected_services', models.JSONField(default=list)),
                ('duration_years', models.PositiveSmallIntegerField(choices=[(3, '3 Years'), (5, '5 Years')])),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('CONTRACTED', 'Contracted'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=15)),
                ('review_notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='clients.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_service_requests', to=settings.AUTH_USER_MODEL)),
                ('vehicles', models.ManyToManyField(blank=True, related_name='service_requests', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'service_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
