# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('request_type', models.CharField(choices=[('ROUTINE', 'Routine Maintenance'), ('BREAKDOWN', 'Breakdown'), ('REPAIR', 'Repair'), ('INSPECTION', 'Inspection'), ('ACCIDENT', 'Accident / Damage')], max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('location_description', models.CharField(blank=True, max_length=255)),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_provider_name', models.CharField(blank=True, max_length=200)),
                ('service_provider_contact', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], db_index=True, default='SUBMITTED', max_length=15)),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True)),
                ('assigned_officer', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['NAMRENT_ADMIN', 'NAMRENT_OPS']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='clients.client')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_maintenance', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'maintenance_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='maintenance_status_b8d89d_idx'), models.Index(fields=['client', 'status'], name='maintenance_client__d48aa4_idx')],
            },
        ),
    ]
