# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dealers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeInRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('trade_in_mileage', models.PositiveIntegerField(help_text='Mileage at time of trade-in request')),
                ('trade_in_condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor')], max_length=10)),
                ('trade_in_notes', models.TextField(blank=True)),
                ('replacement_vehicle_type', models.CharField(blank=True, max_length=10)),
                ('replacement_requirements', models.TextField(blank=True)),
                ('selected_services', models.JSONField(default=list)),
                ('duration_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('VALUATION_REQUESTED', 'Valuation Requested'), ('VALUATION_SUBMITTED', 'Valuation Submitted'), ('VALUATION_ACCEPTED', 'Valuation Accepted'), ('REPLACEMENT_REQUESTED', 'Replacement Requested'), ('OFFER_RECEIVED', 'Offer Received'), ('APPROVED', 'Approved'), ('CONTRACTED', 'Contracted'), ('ACTIVE', 'Active')], db_index=True, default='DRAFT', max_length=25)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_valuation_dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_requests', to='dealers.dealer')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_in_requests', to='clients.client')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_tradeins', to=settings.AUTH_USER_MODEL)),
                ('trade_in_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_in_requests', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'trade_in_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeInValuation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('condition_notes', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('valuation_date', models.DateField()),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='dealers.dealer')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_valuations', to=settings.AUTH_USER_MODEL)),
                ('trade_in_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='tradeins.tradeinrequest')),
            ],
            options={
                'db_table': 'trade_in_valuations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tradeinrequest',
            name='accepted_valuation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for', to='tradeins.tradeinvaluation'),
        ),
    ]
