# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted'), ('STATUS_CHANGED', 'Status Changed'), ('DOCUMENT_UPLOADED', 'Document Uploaded'), ('COMMENT_ADDED', 'Comment Added'), ('ASSIGNED', 'Assigned'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SENT', 'Sent'), ('PAYMENT_RECORDED', 'Payment Recorded'), ('OFFER_SUBMITTED', 'Offer Submitted'), ('VALUATION_SUBMITTED', 'Valuation Submitted')], db_index=True, max_length=30)),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('entity_display', models.CharField(blank=True, help_text='Human-readable entity label', max_length=255)),
                ('diff', models.JSONField(blank=True, help_text='Dict of changed field: [old, new]', null=True)),
                ('note', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
