# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('dealers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('vin', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('colour', models.CharField(blank=True, max_length=50)),
                ('vehicle_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('SUV', 'SUV'), ('PICKUP', 'Pickup'), ('VAN', 'Van'), ('BUS', 'Bus'), ('TRUCK', 'Truck'), ('OTHER', 'Other')], max_length=10)),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('ELECTRIC', 'Electric'), ('HYBRID', 'Hybrid')], max_length=10)),
                ('transmission', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], max_length=10)),
                ('mileage', models.PositiveIntegerField(default=0, help_text='Kilometres')),
                ('mileage_last_updated', models.DateField(blank=True, null=True)),
                ('ownership_type', models.CharField(choices=[('CLIENT_OWNED', 'Client-Owned'), ('NAMRENT_OWNED', 'NamRent-Owned'), ('DEALER_SUPPLIED', 'Dealer-Supplied'), ('LEASE', 'Lease Vehicle'), ('TRADE_IN', 'Trade-In Vehicle')], max_length=20)),
                ('current_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_ONBOARDING', 'Pending Onboarding'), ('UNDER_MAINTENANCE', 'Under Maintenance'), ('OUT_OF_SERVICE', 'Out of Service'), ('PENDING_TRADE_IN', 'Pending Trade-In'), ('RETURNED', 'Returned'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING_ONBOARDING', max_length=25)),
                ('insurance_provider', models.CharField(blank=True, max_length=200)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_start', models.DateField(blank=True, null=True)),
                ('insurance_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('license_expiry', models.DateField(blank=True, db_index=True, null=True)),
                ('tracking_provider', models.CharField(blank=True, max_length=200)),
                ('tracking_device_id', models.CharField(blank=True, max_length=100)),
                ('tracking_status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('NOT_INSTALLED', 'Not Installed')], default='NOT_INSTALLED', max_length=15)),
                ('tracking_renewal_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='clients.client')),
                ('assigned_driver', models.ForeignKey(blank=True, limit_choices_to={'role': 'CLIENT_USER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to=settings.AUTH_USER_MODEL)),
                ('dealer_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_vehicles', to='dealers.dealer')),
            ],
            options={
                'db_table': 'vehicles',
                'ordering': ['make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='VehicleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_assignments', to='clients.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assignments', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='vehicles.vehicle')),
            ],
            options={
                'db_table': 'vehicle_assignments',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['insurance_expiry'], name='vehicles_insuran_8be625_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['license_expiry'], name='vehicles_license_9ef8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicle',
            index=models.Index(fields=['current_status'], name='vehicles_current_4daeed_idx'),
        ),
    ]
