# Generated by Django 5.2.14 on 2026-05-14 07:15

import apps.documents.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=apps.documents.models.document_upload_path)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('document_category', models.CharField(choices=[('CLIENT', 'Client Document'), ('VEHICLE', 'Vehicle Document'), ('DEALER', 'Dealer Document'), ('INSURANCE', 'Insurance Document'), ('LICENSING', 'Licensing Document'), ('CONTRACT', 'Contract'), ('INVOICE', 'Invoice'), ('SERVICE_REPORT', 'Service Report'), ('TRADE_IN', 'Trade-In Document'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('object_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('SUPERSEDED', 'Superseded')], default='ACTIVE', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
