# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('pathway_type', models.CharField(choices=[('EXISTING_FLEET', 'Existing Fleet Management'), ('NEW_PROCUREMENT', 'New Vehicle Procurement'), ('TRADE_IN', 'Trade-In + Replacement')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(db_index=True)),
                ('duration_months', models.PositiveSmallIntegerField()),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('services_included', models.JSONField(default=list)),
                ('payment_schedule', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed')], db_index=True, default='DRAFT', max_length=20)),
                ('renewal_status', models.CharField(choices=[('NOT_DUE', 'Not Due'), ('PENDING', 'Pending Renewal'), ('RENEWED', 'Renewed'), ('LAPSED', 'Lapsed')], default='NOT_DUE', max_length=10)),
                ('renewal_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='clients.client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('renewed_by_contract', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renews_contract', to='contracts.contract')),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
