# Generated by Django 5.2.14 on 2026-05-14 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('documents', '0001_initial'),
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='signed_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to='documents.document'),
        ),
        migrations.AddField(
            model_name='contract',
            name='vehicles',
            field=models.ManyToManyField(blank=True, related_name='contracts', to='vehicles.vehicle'),
        ),
    ]
